dist: trusty
sudo: required

language: node_js
node_js:
  - "6"

os:
  - linux

before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sleep 3;
    fi
  - pushd /tmp
  - wget https://github.com/LaurentTreguier/sdlang-vscode/archive/master.zip -O sdlang.zip
  - unzip sdlang.zip
  - mkdir -p ~/.vscode/extensions
  - mv sdlang-vscode-master ~/.vscode/extensions
  - popd

install:
  - npm install
  - npm run vscode:prepublish

before_script:
  - sudo wget http://master.dl.sourceforge.net/project/d-apt/files/d-apt.list -O /etc/apt/sources.list.d/d-apt.list
  - sudo apt-get update -qq
  - sudo apt-get -y --allow-unauthenticated install --reinstall d-apt-keyring
  - sudo apt-get update -qq
  - sudo apt-get -y install dmd-bin dub libsecret-1-0

script:
  - npm test --silent

after_success:
  - bash <(curl -s https://codecov.io/bash)